### ISSUE TITLE
SyntaxError: Invalid character

### ISSUE THREAD

**Issue by mistakia** [hacdias/human-to-milliseconds#1]
Hey - I'm using `js-ipfs` on mobile via `nodejs-mobile` and run into an invalid character error caused by the following [line](https://github.com/hacdias/human-to-milliseconds/blob/master/src/index.js#L12).

```
  µs: 0.001
  ^

SyntaxError: Invalid character
   at createScript (vm.js:80:3)
   at runInThisContext (vm.js:139:3)
   at Module.prototype._compile (module.js:588:3)
   at Module._extensions[.js] (module.js:635:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.runMain (module.js:665:3)
   at startup (bootstrap_node.js:188:9)
   at Anonymous function (bootstrap_node.js:611:3)
```

**Comment by mistakia** [comment]
Using [ds300/patch-package](https://github.com/ds300/patch-package) to address the issue as it has more to do with nodejs-mobile, see janeasystems/nodejs-mobile#82
